Used action ids

diff --git a/.github/workflows/validate-version.yml b/.github/workflows/validate-version.yml
--- a/.github/workflows/validate-version.yml
+++ b/.github/workflows/validate-version.yml
@@ -14,7 +14,8 @@ jobs:
       - name: Assign new version string
         run: |
           NEW_VERSION=`cat Assets/Resources/VERSION.txt`
-          echo $NEW_VERSION
+          echo '::set-output name=VERSION::'$NEW_VERSION
+        id: branch
       
       - name: Checkout master branch
         uses: actions/checkout@v2
@@ -24,7 +25,8 @@ jobs:
       - name: Assign old version string
         run: |
           OLD_VERSION=`cat Assets/Resources/VERSION.txt`
-          echo $OLD_VERSION
+          echo '::set-output name=VERSION::'$OLD_VERSION
+        id: master
 
       - name: Download semver script
         run: |
@@ -33,6 +35,6 @@ jobs:
       
       - name: Compare semvers
         run: |
-          echo $NEW_VERSION
-          echo $OLD_VERSION
-          ./semver2.sh $NEW_VERSION $OLD_VERSION | { read -r var; if [ "$var" -gt 0 ]; then exit 0; else echo "AntiquatedVersionError: upstream version ($NEW_VERSION) is <= master branch version ($OLD_VERSION). Please update VERSION.txt to newer semantic version before merging." && exit 1; fi; }
+          NEW_VERSION=`echo ${{ steps.branch.outputs.VERSION }}`
+          OLD_VERSION=`echo ${{ steps.master.outputs.VERSION }}`
+          ./semver2.sh $NEW_VERSION $OLD_VERSION | { read -r var; if [ "$var" -gt 0 ]; then exit 0; else echo "AntiquatedVersionError: upstream version ("$NEW_VERSION") is <= master branch version ("$OLD_VERSION"). Please update VERSION.txt to newer semantic version before merging." && exit 1; fi; }
